//
// autogenerated type definitions
//
function pad(): any {}
function mix(): any {}
function augment(): any {}
function supplement(): any {}
function before(): any {}
function after(): any {}
function chain(): any {}
function isFun(): any {}
function isObj(): any {}
function isString(): any {}
function isNumber(): any {}
function isFrame(): any {}
function isArray(): any {}
function isEmpty(): any {}
function abs(): any {}
function pow(): any {}
function sqrt(): any {}
function min(): any {}
function max(): any {}
function ceil(): any {}
function floor(): any {}
function round(): any {}
function sin(): any {}
function cos(): any {}
function tan(): any {}
function acos(): any {}
function asin(): any {}
function atan(): any {}
function atan2(): any {}
function rnd(): any {}
function RND(): any {}
function limit(): any {}
function within(): any {}
function warp(): any {}
function lerp(): any {}
function map(): any {}
function dist(): any {}
function length(): any {}
function angle(): any {}
function bearing(): any {}
function kill(): any {}
function sfx(): any {}
function width(): any {}
function height(): any {}
function rx(): any {}
function ry(): any {}
function save(): any {}
function restore(): any {}
function scale(): any {}
function rotate(): any {}
function translate(): any {}
function clip(): any {}
function smooth(): any {}
function blocky(): any {}
function alpha(): any {}
function stroke(): any {}
function lineWidth(): any {}
function fill(): any {}
function background(): any {}
function line(): any {}
function plot(): any {}
function triangle(): any {}
function quad(): any {}
function rect(): any {}
function circle(): any {}
function ellipse(): any {}
function arc(): any {}
function earc(): any {}
function polygon(): any {}
function moveTo(): any {}
function lineTo(): any {}
function arcTo(): any {}
function quadraticTo(): any {}
function bezierTo(): any {}
function close(): any {}
function shape(): any {}
function font(): any {}
function alignLeft(): any {}
function alignCenter(): any {}
function alignRight(): any {}
function baseTop(): any {}
function baseMiddle(): any {}
function baseBottom(): any {}
function text(): any {}
function textWidth(): any {}
function textHeight(): any {}
function image(): any {}
function rgb(): any {}
function rgba(): any {}
function RGB(): any {}
function RGBA(): any {}
function hsl(): any {}
function hsla(): any {}

// root mod
var $ = <any>{
    res:  {
    },
    alt:  {
            key:  {
                    name:  1,
        },
            pad:  function(): any {},
            mouse:  {
                    name:  1,
        },
            mix:  function(): any {},
            augment:  function(): any {},
            supplement:  function(): any {},
            before:  function(): any {},
            after:  function(): any {},
            chain:  function(): any {},
            isFun:  function(): any {},
            isObj:  function(): any {},
            isString:  function(): any {},
            isNumber:  function(): any {},
            isFrame:  function(): any {},
            isArray:  function(): any {},
            isEmpty:  function(): any {},
            E:  1,
            PI:  1,
            PI2:  1,
            TAU:  1,
            HALF_PI:  1,
            abs:  function(): any {},
            pow:  function(): any {},
            sqrt:  function(): any {},
            min:  function(): any {},
            max:  function(): any {},
            ceil:  function(): any {},
            floor:  function(): any {},
            round:  function(): any {},
            sin:  function(): any {},
            cos:  function(): any {},
            tan:  function(): any {},
            acos:  function(): any {},
            asin:  function(): any {},
            atan:  function(): any {},
            atan2:  function(): any {},
            rnd:  function(): any {},
            RND:  function(): any {},
            limit:  function(): any {},
            within:  function(): any {},
            warp:  function(): any {},
            lerp:  function(): any {},
            map:  function(): any {},
            dist:  function(): any {},
            length:  function(): any {},
            angle:  function(): any {},
            bearing:  function(): any {},
            kill:  function(): any {},
            sfx:  function(): any {},
            width:  function(): any {},
            height:  function(): any {},
            rx:  function(): any {},
            ry:  function(): any {},
            save:  function(): any {},
            restore:  function(): any {},
            scale:  function(): any {},
            rotate:  function(): any {},
            translate:  function(): any {},
            clip:  function(): any {},
            smooth:  function(): any {},
            blocky:  function(): any {},
            alpha:  function(): any {},
            stroke:  function(): any {},
            lineWidth:  function(): any {},
            fill:  function(): any {},
            background:  function(): any {},
            line:  function(): any {},
            plot:  function(): any {},
            triangle:  function(): any {},
            quad:  function(): any {},
            rect:  function(): any {},
            circle:  function(): any {},
            ellipse:  function(): any {},
            arc:  function(): any {},
            earc:  function(): any {},
            polygon:  function(): any {},
            moveTo:  function(): any {},
            lineTo:  function(): any {},
            arcTo:  function(): any {},
            quadraticTo:  function(): any {},
            bezierTo:  function(): any {},
            close:  function(): any {},
            shape:  function(): any {},
            font:  function(): any {},
            alignLeft:  function(): any {},
            alignCenter:  function(): any {},
            alignRight:  function(): any {},
            baseTop:  function(): any {},
            baseMiddle:  function(): any {},
            baseBottom:  function(): any {},
            text:  function(): any {},
            textWidth:  function(): any {},
            textHeight:  function(): any {},
            image:  function(): any {},
            rgb:  function(): any {},
            rgba:  function(): any {},
            RGB:  function(): any {},
            RGBA:  function(): any {},
            hsl:  function(): any {},
            hsla:  function(): any {},
    },
    dna:  {
            Emitter:  function(): any {},
            Grid:  function(): any {},
            SlideCamera:  function(): any {},
            text:  {
                    blinkingText:  function(): any {},
                    fadeText:  function(): any {},
                    scroll:  function(): any {},
        },
            Tiles:  function(): any {},
            hud:  {
                    Container:  function(): any {},
                    gadget:  {
                            Button:  function(): any {},
                            Slider:  function(): any {},
                            Console:  function(): any {},
                            DynamicList:  function(): any {},
                            Explorer:  function(): any {},
                            Eyes:  function(): any {},
                            FrameInspector:  function(): any {},
                            ImageButton:  function(): any {},
                            ImageInspector:  function(): any {},
                            Label:  function(): any {},
                            Magnify:  function(): any {},
                            TextPane:  function(): any {},
                            TextView:  function(): any {},
                            NodeInspector:  function(): any {},
                            Progress:  function(): any {},
            },
                    Window:  function(): any {},
                    Pane:  function(): any {},
                    MonoContainer:  function(): any {},
                    Hud:  function(): any {},
                    trait:  {
                            Component:  {
                },
                            Draggable:  {
                                    onMouseDrag:  function(): any {},
                },
                            name:  1,
            },
        },
            A1:  function(): any {},
            Main:  function(): any {},
    },
    lib:  {
            asserts:  {
                    assertTrue:  function(): any {},
                    assertNumber:  function(): any {},
                    notEmpty:  function(): any {},
                    name:  1,
        },
            img:  {
                    TileSet:  function(): any {},
                    screenshot:  function(): any {},
                    screenshotArea:  function(): any {},
                    downloadDataURL:  function(): any {},
                    imgToCanvas:  function(): any {},
                    imgToDataURL:  function(): any {},
                    imgData:  function(): any {},
                    name:  1,
        },
            math:  {
                    name:  1,
                    PI:  1,
                    PI2:  1,
                    length:  function(): any {},
                    normalize:  function(): any {},
                    distance:  function(): any {},
                    distanceSq:  function(): any {},
                    distanceToSegmentSq:  function(): any {},
                    distanceToSegment:  function(): any {},
                    targetAngle:  function(): any {},
                    normalizeAngle:  function(): any {},
                    reverseAngle:  function(): any {},
                    limit:  function(): any {},
                    linear:  function(): any {},
                    dotProduct:  function(): any {},
                    vecAngle:  function(): any {},
                    vecX:  function(): any {},
                    vecY:  function(): any {},
                    degToRad:  function(): any {},
                    radToDeg:  function(): any {},
                    rndf:  function(): any {},
                    rndfi:  function(): any {},
                    rnd:  function(): any {},
                    rndi:  function(): any {},
                    rnds:  function(): any {},
                    rnde:  function(): any {},
        },
            objUtil:  {
                    assertIsPositionalObj:  function(): any {},
                    distance:  function(): any {},
                    vector:  function(): any {},
                    nVector:  function(): any {},
                    findObj:  function(): any {},
                    findObjInRadius:  function(): any {},
                    rayTrace:  function(): any {},
                    rayTraceRadial:  function(): any {},
                    name:  1,
        },
            sfx:  function(): any {},
            hud:  {
                    style:  function(): any {},
                    line:  function(): any {},
                    rect:  function(): any {},
                    panel:  function(): any {},
                    button:  function(): any {},
                    name:  1,
        },
            physics:  {
                    EventObject:  function(): any {},
                    Area2D:  function(): any {},
                    KinematicObject2D:  function(): any {},
                    Collidable2D:  function(): any {},
                    MathUtil:  function(): any {},
                    Mesh2D:  function(): any {},
                    Section2D:  function(): any {},
                    SquareMesh2D:  function(): any {},
                    Vector2D:  function(): any {},
        },
            Asserts:  function(): any {},
    },
    env:  {
            hud:  {
                    font:  1,
                    base:  1,
                    'base.hi':  1,
                    'base.low':  1,
                    content:  1,
                    'content.low':  1,
                    'content.hi':  1,
                    'content.yellow':  1,
                    'content.orange':  1,
                    'content.red':  1,
                    'content.magenta':  1,
                    'content.violet':  1,
                    'content.blue':  1,
                    'content.cyan':  1,
                    'content.green':  1,
                    line:  1,
                    baseHeight:  1,
                    background:  {
                            base:  1,
            },
                    title:  {
                            content:  1,
                            font:  1,
            },
                    window:  {
                            content:  1,
                            tag:  {
                                    'base.hi':  1,
                                    base:  1,
                },
                            bar:  {
                                    base:  1,
                },
                            control:  {
                                    base:  1,
                                    content:  1,
                },
            },
                    name:  1,
        },
    },
    lab:  {
            background:  {
                    draw:  function(): any {},
                    name:  1,
        },
    },
    cue:  {
    },
    job:  {
    },
    mod:  function(): any {},
    trap:  function(): any {},
    sys:  {
            mix:  1,
            augment:  1,
            supplement:  1,
            before:  1,
            after:  1,
            chain:  1,
            Frame:  function(): any {},
            LabFrame:  function(): any {},
            isObj:  1,
            isFun:  1,
            isNumber:  1,
            isString:  1,
            isArray:  1,
            isMutable:  function(): any {},
            isFrame:  1,
            isEmpty:  1,
    },
    pub:  {
    },
    log:  function(): any {},
    boot:  {
            init:  function(): any {},
            evo:  function(): any {},
            draw:  function(): any {},
            name:  1,
    },
    pak:  {
            load:  1,
            mount:  1,
            fixMode:  1,
            name:  1,
    },
    setup:  function(): any {},
    test:  {
            mathUtilTest:  function(): any {},
    },
}

// local context
var sys = <any>{
    mix:  1,
    augment:  1,
    supplement:  1,
    before:  1,
    after:  1,
    chain:  1,
    Frame:  function(): any {},
    LabFrame:  function(): any {},
    isObj:  1,
    isFun:  1,
    isNumber:  1,
    isString:  1,
    isArray:  1,
    isMutable:  function(): any {},
    isFrame:  1,
    isEmpty:  1,
}
var lib = <any>{
    asserts:  {
            assertTrue:  function(): any {},
            assertNumber:  function(): any {},
            notEmpty:  function(): any {},
            name:  1,
    },
    img:  {
            TileSet:  function(): any {},
            screenshot:  function(): any {},
            screenshotArea:  function(): any {},
            downloadDataURL:  function(): any {},
            imgToCanvas:  function(): any {},
            imgToDataURL:  function(): any {},
            imgData:  function(): any {},
            name:  1,
    },
    math:  {
            name:  1,
            PI:  1,
            PI2:  1,
            length:  function(): any {},
            normalize:  function(): any {},
            distance:  function(): any {},
            distanceSq:  function(): any {},
            distanceToSegmentSq:  function(): any {},
            distanceToSegment:  function(): any {},
            targetAngle:  function(): any {},
            normalizeAngle:  function(): any {},
            reverseAngle:  function(): any {},
            limit:  function(): any {},
            linear:  function(): any {},
            dotProduct:  function(): any {},
            vecAngle:  function(): any {},
            vecX:  function(): any {},
            vecY:  function(): any {},
            degToRad:  function(): any {},
            radToDeg:  function(): any {},
            rndf:  function(): any {},
            rndfi:  function(): any {},
            rnd:  function(): any {},
            rndi:  function(): any {},
            rnds:  function(): any {},
            rnde:  function(): any {},
    },
    objUtil:  {
            assertIsPositionalObj:  function(): any {},
            distance:  function(): any {},
            vector:  function(): any {},
            nVector:  function(): any {},
            findObj:  function(): any {},
            findObjInRadius:  function(): any {},
            rayTrace:  function(): any {},
            rayTraceRadial:  function(): any {},
            name:  1,
    },
    sfx:  function(): any {},
    hud:  {
            style:  function(): any {},
            line:  function(): any {},
            rect:  function(): any {},
            panel:  function(): any {},
            button:  function(): any {},
            name:  1,
    },
    physics:  {
            EventObject:  function(): any {},
            Area2D:  function(): any {},
            KinematicObject2D:  function(): any {},
            Collidable2D:  function(): any {},
            MathUtil:  function(): any {},
            Mesh2D:  function(): any {},
            Section2D:  function(): any {},
            SquareMesh2D:  function(): any {},
            Vector2D:  function(): any {},
    },
    Asserts:  function(): any {},
}
var res = <any>{
}
var dna = <any>{
    Emitter:  function(): any {},
    Grid:  function(): any {},
    SlideCamera:  function(): any {},
    text:  {
            blinkingText:  function(): any {},
            fadeText:  function(): any {},
            scroll:  function(): any {},
    },
    Tiles:  function(): any {},
    hud:  {
            Container:  function(): any {},
            gadget:  {
                    Button:  function(): any {},
                    Slider:  function(): any {},
                    Console:  function(): any {},
                    DynamicList:  function(): any {},
                    Explorer:  function(): any {},
                    Eyes:  function(): any {},
                    FrameInspector:  function(): any {},
                    ImageButton:  function(): any {},
                    ImageInspector:  function(): any {},
                    Label:  function(): any {},
                    Magnify:  function(): any {},
                    TextPane:  function(): any {},
                    TextView:  function(): any {},
                    NodeInspector:  function(): any {},
                    Progress:  function(): any {},
        },
            Window:  function(): any {},
            Pane:  function(): any {},
            MonoContainer:  function(): any {},
            Hud:  function(): any {},
            trait:  {
                    Component:  {
            },
                    Draggable:  {
                            onMouseDrag:  function(): any {},
            },
                    name:  1,
        },
    },
    A1:  function(): any {},
    Main:  function(): any {},
}
var env = <any>{
    hud:  {
            font:  1,
            base:  1,
            'base.hi':  1,
            'base.low':  1,
            content:  1,
            'content.low':  1,
            'content.hi':  1,
            'content.yellow':  1,
            'content.orange':  1,
            'content.red':  1,
            'content.magenta':  1,
            'content.violet':  1,
            'content.blue':  1,
            'content.cyan':  1,
            'content.green':  1,
            line:  1,
            baseHeight:  1,
            background:  {
                    base:  1,
        },
            title:  {
                    content:  1,
                    font:  1,
        },
            window:  {
                    content:  1,
                    tag:  {
                            'base.hi':  1,
                            base:  1,
            },
                    bar:  {
                            base:  1,
            },
                    control:  {
                            base:  1,
                            content:  1,
            },
        },
            name:  1,
    },
}
var lab = <any>{
    background:  {
            draw:  function(): any {},
            name:  1,
    },
}
var mod = function(): any {}
var pub = <any>{
}
var cue = <any>{
}
var job = <any>{
}
var trap = function(): any {}
